### ISSUE TITLE
Can we have a comprehensive list of ads played by youtube (specifically youtube) ?

### ISSUE THREAD

**Issue by hhammoud01** [Trellmor/bind-adblock#25]

**Comment by Trellmor** [comment]
There are [other projects](https://www.sunshine.it/disable-youtube-video-advertising-with-pi-hole-finally-video-2/) that provide block lists. You can add them to your config and see if it works. This project is about aggregation existing block lists and combining them into bind zonefiles. I'm not providing block lists of my own.

Blocking youtube ads with dns doesn't seem to work nowadays since youtube uses the same hostnames for ads and content.
